name: pynteny-dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - semidan.robaina
dependencies:
  - python <= 3.10
  - poetry
  - pip
  - hmmer
  - prodigal
  - pyfastx >=0.8
  - biopython
  - numpy
  - pandas
  - psutil
  - python-wget
  - streamlit
  - streamlit-aggrid