name: pynteny-dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - semidan.robaina
dependencies:
  - python >= 3.10
  - poetry >= 1.3
  - pip >= 22.3
  - hmmer >= 3.3
  - prodigal >= 2.6
  - pyfastx >=0.8
  - biopython >= 1.8
  - numpy
  - pandas
  - psutil >= 5.9
  - python-wget 
  - streamlit=1.16
  - streamlit-aggrid