site_name: Pynteny
site_url: https://robaina.github.io/Pynteny
repo_url: https://github.com/Robaina/Pynteny
site_author: Semidán Robaina
nav:
    - Home: index.md
    - Subcommands:
        - Search: search.md
        - Build: build.md
        - Parse: parse.md
        - Download: download.md
        - App: app.md
    - 
theme: readthedocs
# Add MathJax support:
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js