site_name: Pynteny
site_url: https://robaina.github.io/Pynteny
repo_url: https://github.com/Robaina/Pynteny
site_author: Semidán Robaina
nav:
    - Home: index.md
    - Subcommands:
        - Search: subcommands/search.md
        - Build: subcommands/build.md
        - Parse: subcommands/parse.md
        - Download: subcommands/download.md
        - App: subcommands/app.md
    - Examples:
         - Example CLI: examples/example_cli.ipynb
         - Example API: examples/example_api.ipynb
         - Sus operon: examples/example_sus.ipynb
    - References: references.md
theme: readthedocs
plugins:
  - mkdocs-jupyter
  - mkdocstrings
# Add MathJax support:
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js